select * from restaurants;

-- list top 5 cuisines as per revenue by top 5 restaurants of every cuisine.
select cuisine, sum(rating_count*cost) as 'total_revenue' from 
(select *, rating_count*cost, row_number() over(partition by cuisine order by rating_count*cost desc) 
as 'rank' from restaurants)t where t.rank < 6
group by cuisine order by 
total_revenue desc;

-- what % of total revenue is generated by top 1% restaurants
select sum(rating_count*cost)as 'revenue' from 
(select *, rating_count*cost , row_number() over( order by rating_count*cost desc)
as 'rank' from restaurants) t where t.rank <=614;

-- what % of revenue is generated by top 20% of restaurants with respect to total revenue?
with 
	q1 as (select sum(rating_count*cost)as 'top_revenue' from 
	(select *, rating_count*cost , row_number() over( order by rating_count*cost desc)
	as 'rank' from restaurants) t where t.rank <=12280),
	q2 as (select sum(rating_count*cost) as 'total_revenue' from restaurants)
 select (top_revenue/total_revenue)*100 as 'revenue_percentage' from q1,q2